spring:
  datasource:
    url: jdbc:postgresql://localhost:49153/postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
