spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

logging:
  level:
    "[org.hibernate]":
      SQL: DEBUG