spring:
  datasource:
    url: jdbc:postgresql://localhost:49155/postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      springframework:
        security: DEBUG
